{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8s-service.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best practices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    helm.sh/chart: {{ include "k8s-service.chart" . }}
    app.kubernetes.io/name: {{ include "k8s-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.hpaLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.hpaAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8s-service.fullname" . }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  {{ if .Values.horizontalPodAutoscaler.avgCpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.avgCpuUtilization }}
  {{- end }}
  {{ if .Values.horizontalPodAutoscaler.avgMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.avgMemoryUtilization }}
  {{- end }}
  {{ range .Values.horizontalPodAutoscaler.externalMetrics }}
    - type: External
      external:
        metric:
          name: {{ .metricName }}
          selector:
            matchLabels: 
{{ toYaml .matchLabels | indent 14 }}
        target:
        {{ if .targetAverageValue }}
          type: "AverageValue"
          averageValue: {{ .targetAverageValue }}
        {{- end }}
        {{ if .targetValue }}
          type: "Value"
          value: {{ .targetValue }}
        {{- end }}
  {{- end }}
{{- end }}
